name: my_flutter_curriculum
description: My curriculum made with Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  getflutter: ^1.0.3
  badges: ^1.1.0
  webview_flutter: ^0.3.19+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/apps/acta/
    - assets/apps/heremycard/
    - assets/apps/neverforget/
